### ISSUE TITLE
About parameters to use when predicting with --scale_hic_using_powerlaw on

### ISSUE THREAD

**Issue by aldenleung** [broadinstitute/ABC-Enhancer-Gene-Prediction#136]
Hello, thanks for the wonderful algorithm. I am able to run the pipeline successfully according to the sample codes on the page but I have one question about how to input the powerlaw fit parameters during prediction. 
Here is my step:

Step 1. Run run.neighborhoods.py. 

Step 2. Create inputs from raw HiC files. I ran both juicebox_dump.py and compute_powerlaw_fit_from_hic.py. This gives outputs in HiCdir/chr*/ and powerlaw fit files in HiCdir/powerlaw/hic.powerlaw.txt and HiCdir/powerlaw/hic.mean_var.txt

Step 3. Run predict.py. I run predict.py with --scale_hic_using_powerlaw. 
Here is the question in step 3. I may have misunderstood the example but I found no indication about how the powerlaw fit files are used in predict.py. Will predict.py directly looks for the powerfit files in HiCdir/powerlaw/? Or should one set --hic_gamma or --hic_gamma_reference? If so, which values should I take from hic.powerlaw.txt or hic.mean_var.txt as --hic_gamma and --hic_gamma_reference?

Thanks a lot!

**Comment by atancoder** [comment]
for the powerlaw fit, you'd just pass `hic_gamma` in the predict step (don't pass in the reference). You'd obtain gamma from hic.powerlaw.txt

**Comment by tan5251** [comment]
When I have experimental HiC data, should I predict with -scale_hic_using_powerlaw on?
