### ISSUE TITLE
  File "makeCandidateRegions.py", line 5, in <module>     from peaks import * ModuleNotFoundError: No module named 'peaks'

### ISSUE THREAD

**Issue by ishtiaqueh** [broadinstitute/ABC-Enhancer-Gene-Prediction#17]
Hi,

Thank you for this extremely resourceful code. I have been trying to run the model on my cell line. I am quite new to bioinformatics, but when I run makeCandidateRegions.py I get the following error:
  File "makeCandidateRegions.py", line 5, in <module>
    from peaks import *
ModuleNotFoundError: No module named 'peaks'

Can you please help me solve this issue.

Thank you.

**Comment by jnasser3** [comment]
Hi, glad you find the code useful.

This sounds like a python path issue. Can you ensure that the src/peaks.py file is in the same directory as src/makeCandidateRegions.py? That usually solves the problem.

If this still doesn't solve the problem, you should check your environment setup - googling the error is also helpful. This sounds like an environment issue specific to your system and not related to the ABC code repository.
