### ISSUE TITLE
load_hic_avg expects three columns, but the recommended average hic bed files have four columns

### ISSUE THREAD

**Issue by pl92297** [broadinstitute/ABC-Enhancer-Gene-Prediction#172]
Hi, 

There is currently an error while using the average hic files that are recommended in the documentation (https://www.encodeproject.org/files/ENCFF134PUN/@@download/ENCFF134PUN.bed.gz). The `load_hic_avg` function that the prediction script uses to load the hic files expects three columns (`cols = {"x1": np.int64, "x2": np.int64, "hic_contact": np.float64})`) but the files actually have four columns (chr window1 window2 contact) and therefore cannot be read. Please edit the function to account for the additional chromosome column or reupload the average files without the first column. 

Thanks!

**Comment by maxdudek** [comment]
I also ran into this problem!

**Comment by atancoder** [comment]
You are not supposed to use the .bed.gz file directly. Did you extract that file into directories and pass in the path to the config in the directory?

**Comment by maxdudek** [comment]
Yes, I ran `workflow/scripts/extract_avg_hic.py` and put the output directory in the config

**Comment by atancoder** [comment]
Thank you both for reporting! I fixed the `extract_avg_hic.py` script so that it doesn't print out the chromosome column into the extracted files. You can run that script again to get things working
