### ISSUE TITLE
Add mouse genome support in juicebox_dump.py and compute_powerlaw_fit_from_hic.py

### ISSUE THREAD

**Issue by zyqfrog10** [broadinstitute/ABC-Enhancer-Gene-Prediction#18]
Hi @jnasser3 ,

I noticed juicebox_dump.py does not support mouse genome if set ``` --chromsomes all```.
It would be nice to add an option like, 
```
parser.add_argument('--genome', choices=['hg', 'mm'], help="The species genome. Currently support human (hg) or mouse (mm).")
```
And in the main code,
```
if args.chromosomes == "all":
        if args.genome == "hg":
            chromosomes = list(range(1,23)) + ['X']
        elif args.genome == "mm":
            chromosomes = list(range(1,20)) + ['X']
        else:
            sys.exit("Error: When render on all chromosomes, please specify the species genome, hg or mm.") # 'import sys' if use this error check. 
```

Similarly, in "compute_powerlaw_fit_from_hic.py", in addition to the genome option, 
```
if args.chr == 'all':
     if args.genome == "hg":
        chromosomes = ['chr' + str(x) for x in  list(range(1,23))] + ['chrX']
     elif args.genome == "mm":
        chromosomes = ['chr' + str(x) for x in  list(range(1,20))] + ['chrX']
    else:
            sys.exit("Error: When run on all chromosomes, please specify the species genome, hg or mm.") 
```

Thank,
YZ

**Comment by jnasser3** [comment]
Thanks for the comment. I do see your point and it would be convenient to have this at times. 

On the other hand, there are many different organisms out there and chromosome naming conventions (eg, inclusion of the 'chr' prefix), so it would be a bit clunky to support everything. At the moment I'd prefer not to over-engineer the code base so I think I'll hold off on this change for the moment.

**Comment by zyqfrog10** [comment]
I see. It is good for the time being.
In my local copy, I have added an --chromsize option and allow the code to figure out the chromosome names from chromsize file, excluding random, chrUn, chrM and chrY if any.
