### ISSUE TITLE
When I have experimental HiC data, should I predict with -scale_hic_using_powerlaw on?

### ISSUE THREAD

**Issue by tan5251** [broadinstitute/ABC-Enhancer-Gene-Prediction#181]
When I have experimental HiC data, should I predict with -scale_hic_using_powerlaw on?

_Originally posted by @tan5251 in https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/issues/136#issuecomment-1874016006_

**Comment by atancoder** [comment]
Yes, we would recommend that
