### ISSUE TITLE
How to Recalculate ABC.Score Values for H3K27ac HiChIP + ATAC Data Analysis?

### ISSUE THREAD

**Issue by Gemma-Zhang-326** [broadinstitute/ABC-Enhancer-Gene-Prediction#183]
Dear authors,

I am very excited to use this wonderful tool, however, I am confused about the outputs of my data.
I'm using H3K27ac HiChIP and ATAC data for ABC analysis. Since I substituted the H3K27ac HiChIP bam files for the H3K27ac ChIP-seq bam files, as you mentioned in #16 , the ABC.Score values have changed somewhat in this situation. I would like to know which columns of values I should recalculate for ABC.Score.

Thank you in advance, and I hope to hear from you soon.

Here I paste my codes below,
```shell
python workflow/scripts/run.neighborhoods.py \
    --candidate_enhancer_regions results/CH/Peaks/CH-ATAC-merge-hg38_peaks.narrowPeak.sorted.candidateRegions.bed \
    --ATAC CH-ATAC-merge-hg38.bam.sorted.bam \
    --default_accessibility_feature ATAC \
    --chrom_sizes reference/hg38/GRCh38_EBV.no_alt.chrom.sizes.tsv \
    --chrom_sizes_bed results/tmp/reference/hg38/GRCh38_EBV.no_alt.chrom.sizes.tsv.bed \
    --outdir results/CH/Neighborhoods \
    --genes reference/hg38/CollapsedGeneBounds.hg38.bed \
    --ubiquitously_expressed_genes reference/UbiquitouslyExpressedGenes.txt \
    --expression_table CHRNA_expression.TPM.txt \
    --H3K27ac H3K27ac_.merge_bwt2pairs_sort.bam 1>CHONABC.log 2>&1


python workflow/scripts/predict.py \
    --enhancers results/CH/Neighborhoods/EnhancerList.txt \
    --outdir results/CH/Predictions \
    --score_column ABC.Score \
    --chrom_sizes reference/hg38/GRCh38_EBV.no_alt.chrom.sizes.tsv \
    --accessibility_feature ATAC \
    --cellType CH \
    --genes results/CH/Neighborhoods/GeneList.txt \
    --hic_file CHhg38_H3K27ac_merge.hic \
    --hic_type hic \
    --hic_resolution 5000  \
    --hic_gamma 0.9682622364325432 \
    --hic_scale 5.290868040455912 \
    --scale_hic_using_powerlaw
```

**Comment by Gemma-Zhang-326** [comment]
After carefully reading your papers and codes, the calculation of ABCScores of HiChIP + ATAC experiments should be normalized_atac * hic_contact, the same as ABCScore.Numerator in the output files named `EnhancerPredictionsAllPutative.tsv.gz`.So the $HiChIP\_ABCScore = \frac{HiChIP\_ABCScore.Numerator}{\sum_{\text{all elements } e \text{ within } 5\text{Mb of } G} HiChIP\_ABCScore.Numerator}$. Hope I understand it successfully.
Does the canonical cutoff of 0.02 still apply in this case? It appears that ABCScores_HiChIP is slightly larger than ABCScores.

Hoping to receive your prompt response.

Yours,
Gemma

**Comment by atancoder** [comment]
the cutoff may change, but we haven't calibrated what the cutoff would be for HiChIP. Instead of thresholding, you can instead opt to take the top N ABC scores

**Comment by atancoder** [comment]
Actually H3k27ac HiChIP is not recommended: https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/issues/206#issuecomment-2012536962
