### ISSUE TITLE
chr9 Hi-C data 

### ISSUE THREAD

**Issue by TakuroIwami** [broadinstitute/ABC-Enhancer-Gene-Prediction#188]
Hi, 
Thank you for providing us such a nice function. 
I tried to download Hi-C data following your guidance, described in "Pipeline to Download Hi-C data"
Code I used is below,
#Download hic matrix file from juicebox
python src/juicebox_dump.py \
--hic_file https://hicfiles.s3.amazonaws.com/hiseq/k562/in-situ/combined_30.hic \
--juicebox "java -jar juicer_tools.jar" \
--outdir example_chr22/input_data/HiC/raw/ 

Though all the output files were created, only chr9 file was empty. I would appreciate it if you could confirm this matter. 

Best regards,
Takuro

**Comment by atancoder** [comment]
I would recommend utilizing the new version of the pipeline: https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main
