### ISSUE TITLE
gene expression input?

### ISSUE THREAD

**Issue by olechnwin** [broadinstitute/ABC-Enhancer-Gene-Prediction#191]
Hi,

How do I specify the gene expression as input? Through out the paper, differential expression genes were mentioned and sound like they are used in the prediction model? But how do I specify it?

Thanks in advance for your help!

**Comment by atancoder** [comment]
ABC doesn't take gene expression as input. Maybe you're referring to the CRISPR dataset, or that we are comparing predictions to gene expression?

**Comment by olechnwin** [comment]
Thank you so much for your reply! I must have misunderstood the paper then. 
I also saw this issue and thought gene expression is one of the input #156 . Is this where you are comparing predictions to gene expression?

**Comment by atancoder** [comment]
in the context of that PR, we are interesting in making predictions only for genes that are expressed. We estimate a gene is expressed by looking at the accessibility at the promoter region, and making sure it meets a threshold. (we don't look at RNA-seq of any sort)
