### ISSUE TITLE
Documentation for outputs in Predictions folder

### ISSUE THREAD

**Issue by olechnwin** [broadinstitute/ABC-Enhancer-Gene-Prediction#194]
Hi,

I'm sorry if I missed this but is there a documentation on what are the output files in Predictions directory?
Is the prediction result that I should be looking at is `EnhancerPredictions_threshold0.02_self_promoter.tsv` ?

Thank you!

**Comment by atancoder** [comment]
yes, that file contains the thresholded predictions that ABC believes are E-G links
