### ISSUE TITLE
ABC with Hg38

### ISSUE THREAD

**Issue by Sylviavictor** [broadinstitute/ABC-Enhancer-Gene-Prediction#197]
Hi Authors,
Thank you for your fantastic tool; however, I am now experiencing a problem while attempting to use HiC data for the Hg38 version of the genome.

This was the Command used:
python ABC-Enhancer-Gene-Prediction/workflow/scripts/predict.py \
--enhancers GrCh38/ABC_output/K562/Neighborhoods/EnhancerList.txt \
--genes GrCh38/ABC_output/K562/Neighborhoods/GeneList.txt \
--hic_file GrCh38/input_data/Hic/4DNFITUOMFUQ.hic \
--chrom_sizes reference/chr_sizes \
--hic_resolution 5000 \
--cellType K562 \
--scale_hic_using_powerlaw \
--outdir GrCh38/ABC_output/K562/Predictions \
--accessibility_feature DHS \
--make_all_putative \
--chromosome chr1,chr2,chr3,chr4,chr5,chr6,chr7,chr8,chr10,chr11,chr12,chr13,chr14,chr15,chr16,chr17,chr18,chr19,chr20,chr21,chr22,chrX,chrM 

Traceback (most recent call last):
  File "ABC-Enhancer-Gene-Prediction/workflow/scripts/predict.py", line 303, in <module>
    main()
  File "ABC-Enhancer-Gene-Prediction/workflow/scripts/predict.py", line 242, in main
    this_chr = make_predictions(
  File "ABC-Enhancer-Gene-Prediction/workflow/scripts/predictor.py", line 24, in make_predictions
    pred = add_powerlaw_to_predictions(pred, args, hic_gamma, hic_scale)
  File "ABC-Enhancer-Gene-Prediction/workflow/scripts/predictor.py", line 337, in add_powerlaw_to_predictions
    pred["powerlaw_contact"] = get_powerlaw_at_distance(
  File "ABC-Enhancer-Gene-Prediction/workflow/scripts/hic.py", line 295, in get_powerlaw_at_distance
    assert scale > 0
TypeError: '>' not supported between instances of 'NoneType' and 'int'

Hope you can help me with this
Thanks,
Sylvia

**Comment by atancoder** [comment]
Looks like you're not passing in the `--hic_scale` parameter to the function. I would recommend using Snakemake instead of running the commands manually. Snakemake will handle filling out all the required parameters for you

**Comment by Sylviavictor** [comment]
Thanks for your reply , I tried adding in the --hic_scale and I am getting a warning " File did not contain SCALE normalization vectors for one or both chromosomes at 5000 BP"

**Comment by atancoder** [comment]
the hic data you provide must have 5k BP resolution and be SCALE normalized
