### ISSUE TITLE
How are precision and recall computed for the example data?

### ISSUE THREAD

**Issue by liviu-** [broadinstitute/ABC-Enhancer-Gene-Prediction#21]
Hi, in [step 3](https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction#step-3-computing-the-abc-score) of the "Running the ABC Model" section in the `README.md` file, it says evaluation shows approximately 70% recall and 60% precision. 

Is it possible to compute these values from the files [here](https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/master/example_chr22/ABC_output/Predictions)? The only way I obtained similar values is as shown below, but I calculated the values incorrectly (for example, the `fn` line would normally also require that `x['nDistalEnhancersPredicted'] == 0` and `1` should probably be `x['nDistalEnhancersPredicted']`)

Could you please point me in the right direction?

Thanks!

```python
df = pd.read_csv('GenePredictionStats.txt', sep='\t')

fp = (df.apply(lambda x: x['nDistalEnhancersPredicted'] if not x['geneIsExpressed'] else 0, axis=1)).sum()
tp = (df.apply(lambda x: x['nDistalEnhancersPredicted'] if x['geneIsExpressed'] else 0, axis=1)).sum()
fn = (df.apply(lambda x: 1 if x['geneIsExpressed'] else 0, axis=1)).sum()
tn = (df.apply(lambda x: 1 if x['nDistalEnhancersPredicted'] == 0 and not x['geneIsExpressed'] else 0, axis=1)).sum()

print([fp, tp, fn, tn])
print('Precision: {:.2}'.format(tp/(tp+fp)))
print('Recall: {:.2}'.format(tp/(tp+fn)))
```
Output:
```
[444.0, 737.0, 310, 72]
Precision: 0.62
Recall: 0.7
```

**Comment by jnasser3** [comment]
Hi,

It's not possible using only the data in this repository.

The stated precision and recall refer to a comparison of ABC predictions to experimental data. The experimental data is not provided as part of this repository (it is available in Supplementary Table 6 of our publication: https://www.nature.com/articles/s41588-019-0538-0). 

The GenePredictionStats.txt file just contains summary statistics of ABC predictions, it does not contain experimental data

In order to compute the precision and recall, we compared the experimental data to genome-wide ABC predictions (note this github repository only contains predictions for chromosome 22)

**Comment by liviu-** [comment]
Thank you very much for your quick response! I initially tried with the supplementary table data, but didn't quite manage to get the right numbers. Perhaps I'm not testing on the right subset of the data?


**K562**

```python3
df1 = pd.read_csv('s6_a.csv', sep='\t', skiprows=1)
df1 = df1[df1['class'] != 'promoter']
df1['predicted'] = df1['ABC Score'] > 0.02

display(df1['Significant'].value_counts())

tn, fp, fn, tp = df1.groupby(['Significant', 'predicted']).count().values[:,1]

print([fp, tp, fn, tn])
print('Precision: {:.2}'.format(tp/(tp+fp)))
print('Recall: {:.2}'.format(tp/(tp+fn)))
```
Output:
```
0    3722
1     141
Name: Significant, dtype: int64

[58, 82, 59, 3664]
Precision: 0.59
Recall: 0.58
```

**Other cells**

```python
df2 = pd.read_csv('s6_b.csv', sep='\t', skiprows=1)
df2 = df2[df2['class'] != 'promoter']
df2['predicted'] = df2['ABC Score'] > 0.02
tn, fp, fn, tp = df2.groupby(['Significant', 'predicted']).count().values[:,1]

print([fp, tp, fn, tn])
print('Precision: {:.2}'.format(tp/(tp+fp)))
print('Recall: {:.2}'.format(tp/(tp+fn)))
```
Output:
```
[87, 43, 7, 860]
Precision: 0.33
Recall: 0.86
```

**Comment by jnasser3** [comment]
Yeah, this is the right idea but need to make a few adjustments:

- The ABC Score threshold we used in the paper is .022
- We consider experimental positives to be enhancer-gene pairs that are significant AND that are activating elements (percent change in gene expression < 0)
- We consider experimental negatives to be enhancer-gene pairs that are non-significant AND where there was sufficient power to detect effects (>80% power to detect 25% effects)

Here's some R code:
```
known <- fread("~/junk/s6a.txt")
known$Predicted <- known$`ABC Score` > .022
known$Regulated <- with(known, Significant & `Fraction change in gene expr` < 0)
known$IncludeInModel <- with(known, class != "promoter" & (Regulated | `Power to detect 25% effects` > .8))
table(known[known$IncludeInModel, c("Regulated","Predicted")])
```

Which yields 76 TP, 53 FP and 33 FN for 59% recall at 70% precision. The same filters should be applied to the non-K562 data

**Comment by liviu-** [comment]
Thank you very much for all your help; this clarifies all my questions!
