### ISSUE TITLE
Install QC

### ISSUE THREAD

**Issue by snglcl** [broadinstitute/ABC-Enhancer-Gene-Prediction#211]
Hello, thank you for this great tool!

I ran the install pipeline, but my QC plots for the snakemake config are quite different from the provided version. Is my ABC not running correctly? I am running abc-env. Thanks!
![QCPlots_snakemakeconfig](https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/assets/165340791/b3f006a1-ca2a-4db1-9c66-2dbd21f73bf1)

**Comment by atancoder** [comment]
are you referring to the QC plots generated from the example run? If so, I wouldn't really compare to the example as it's only based on chromosome 22.

**Comment by snglcl** [comment]
Yes, I was running test file via snakemake -j1, and I was expecting the same QC output at the link.

**Comment by atancoder** [comment]
Which link are you referring to?
