### ISSUE TITLE
Apply ABC model to independent cell types

### ISSUE THREAD

**Issue by NicoleYY77** [broadinstitute/ABC-Enhancer-Gene-Prediction#214]
Hi, I'm wondering that how could I apply this model on new cell type, for example, iPSCs? I can get Dnase-seq, H3K27ac data of iPSCs, and use the average Hi-C data as input, but for the normalization of Hi-C, it seems in need of a quantile reference file:
<img width="791" alt="image" src="https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/assets/104636116/51aaefcd-2289-434a-8bf5-3565b32b457a">

so how should I get a reference file for iPSCs?  really appreciate any help!

**Comment by atancoder** [comment]
You would want to keep the K562 reference file as is. https://abc-enhancer-gene-prediction.readthedocs.io/en/latest/usage/methods.html#quantile-normalization-for-activity
