### ISSUE TITLE
Using our own file of promoters

### ISSUE THREAD

**Issue by Kellydc15** [broadinstitute/ABC-Enhancer-Gene-Prediction#218]
Hello,

I wanted to know the recommendation on users providing their own list of promoters for analysis. We noticed that bidirectional promoters are filtered out and we would like to include a file that incorporates these. Our own list includes promoters based off of our own annotation methods from in-house data, and from Gencode v44. 

Thanks

**Comment by atancoder** [comment]
There are implications to the ABC score when using a different list of promoters. Read more here: https://abc-enhancer-gene-prediction.readthedocs.io/en/latest/usage/methods.html#defining-and-adding-gene-promoters
