### ISSUE TITLE
How to specify more than 2 DHS replication ?

### ISSUE THREAD

**Issue by nttg8100** [broadinstitute/ABC-Enhancer-Gene-Prediction#234]
On the NG2019, the supplementary showed that it has 2 bio replications for DHS. However, the script does not show me that I can specify by adding "," if I have more than one samples. It can be used for the H3K27ac but not for the accessibility bam file (DHS or ATAC). Am I misunderstanding about the pipeline ? If I'm correct, what should I do:
+ Use only one because the performance is similar
+ Remap or combine 2 replications to be one bam file

**Comment by nttg8100** [comment]
I found that the current ABC does not support this but I can manually combine the candidate regions from bed files, then merge them into one.

**Comment by yxmmnn** [comment]
hello nttg8100, if i have more than two H3K27ac biological replicates, how can i tackle it? because only merging the bed file cannot inlcude the activity of H3K27ac biological replicates
