### ISSUE TITLE
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

### ISSUE THREAD

**Issue by divyanshusrivastava** [broadinstitute/ABC-Enhancer-Gene-Prediction#241]
Attribute error after installation. 

Following the documentation on this page - https://abc-enhancer-gene-prediction.readthedocs.io/en/latest/usage/getting_started.html

The command 
`snakemake -j1` throws the error 
> AttributeError: module 'lib' has no attribute 'X509_V_FLAG_NOTIFY_POLICY'

**Comment by mayasheth** [comment]
error addressed here: https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/pull/242
