### ISSUE TITLE
run.neighborhoods.py 'Killed' and no EnhancerList.txt produced

### ISSUE THREAD

**Issue by ahelv** [broadinstitute/ABC-Enhancer-Gene-Prediction#26]
Hello,
I am getting a 'Killed' message after 'Assigning classes to enhancers' when running 'run.neighborhoods.py'. I successfully get the GeneList.txt output but do not get the EnhancerList.txt output file. Before the 'Killed' message, everything appears to be running correctly. 

Below is what happens why I execute 'run.neighborhoods.py'. 

Thank you!

<img width="1563" alt="Screen Shot 2020-07-23 at 11 17 21 AM" src="https://user-images.githubusercontent.com/51717884/88311181-31df3200-ccd6-11ea-8cfe-53adb288003b.png">
<img width="1571" alt="Screen Shot 2020-07-23 at 11 17 51 AM" src="https://user-images.githubusercontent.com/51717884/88311217-3ad00380-ccd6-11ea-885b-4e6b850edee8.png">

**Comment by jnasser3** [comment]
Hi, this is an uncommon place for an error, my first guess is it could be an out of memory error. 

How much memory do you have on this compute node? How many rows are in the --candidate_enhancer_regions file?

Which release of the codebase are you using (v0.2.2?)

**Comment by ahelv** [comment]
Thank you! 
I am using v0.2.2 and running on a 256 GB node with 56 cores. 
the --candidate_enhancer_regions file has 3277941 rows
I initially had 3 slots allocated and maxvmem was just over 6GB but still getting killed. I allocated additional slots and was able to run the code successfully. 

Thanks!

**Comment by jnasser3** [comment]
ok great, I'm glad it got resolved. 

Just as a brief FYI, the default ABC Score threshold of .02 is based on ~150,000 candidate regions (which is the pipeline default) and the optimal threshold is impacted by the total number of regions. So if you're looking to make binary cutoffs on the ABC Score, running the model with 3 million regions will likely require a lower threshold than .02. Perhaps you already know this - and I don't know what the downstream application you have in mind is - but just making sure you were aware of this.
