### ISSUE TITLE
5Mb window size

### ISSUE THREAD

**Issue by girdhar3** [broadinstitute/ABC-Enhancer-Gene-Prediction#28]
why is the default window to 5MB. As Hi-C loops are not very reliable beyond 1-2MB (and for CRISPRi-FlowFISH experiment you set only 0.45MB). When testing ABC methodon the different dataset with available ATAC-seq peaks, I realized that we get more associations (ABC>0.02) when boundary is 1MB (not 5MB) and those associations are even more distal on average.

**Comment by thouis** [comment]
ABC doesn't use Hi-C loops, which, as you note, are not very reliable over longer distances.  It does use the same underlying Hi-C data.  5MB was chosen as a reasonable distance to capture the interactions that we saw in CRISPRi tiling experiments.  The optimal settings will depend on the quality of Hi-C and other genomic data.
