### ISSUE TITLE
run.neighborhoods.py Dimension Mismatch 

### ISSUE THREAD

**Issue by ahelv** [broadinstitute/ABC-Enhancer-Gene-Prediction#31]
Hi, I am getting an AssertionError: dimension mismatch when running run.neighborhoods.py. The error produced is included below. Any insight as to what is causing the error is appreciated!

thanks,
Annika

![Screen Shot 2020-09-04 at 9 21 36 AM](https://user-images.githubusercontent.com/51717884/92253596-50b81300-ee95-11ea-9ce8-348e737211f4.png)

**Comment by thouis** [comment]
Hi, could you try this branch and see if it fixes the issue:
https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/use_pysam

**Comment by ahelv** [comment]
Hi, I tried running with the branch you posted but the issue persists.

**Comment by thouis** [comment]
Hi Annika,

Is there some way we could get copies of the data you're trying to run this on?

**Comment by ahelv** [comment]
Indeed, I first ran into this issue using publicly available data:

DHS: SRX1161152 (replicate 1), and SRX1161153 (replicate 2)
H3k27Ac: SRX3083139

I did not have any issue when using the following H3k27Ac data instead
H3k27Ac: SRX5806607 (replicate 1) and SRX5806608 (replicate 2)  

I have again encountered this same error with some "in house" data.

**Comment by thouis** [comment]
Great.  Which gene annotation file were you using?

**Comment by ahelv** [comment]
I used RefSeqCurated.170308.bed.CollapsedGeneBounds.bed

**Comment by thouis** [comment]
Could I ask you to try one more thing before I align these files and try to run:
-  Could you make sure the ABC_output directory has been removed (to make sure no files are being cached).
- Could you try the no_promoter_overlaps branch?

**Comment by ahelv** [comment]
I tried this and I am still getting the same error

**Comment by atancoder** [comment]
We've revamped the codebase. Please check out https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main and reopen your issue if it still exists
