### ISSUE TITLE
Cool format support

### ISSUE THREAD

**Issue by joachimwolff** [broadinstitute/ABC-Enhancer-Gene-Prediction#37]
Hi,

do you plan to support the read of the cooler file format additional to the hic and bedpe support? https://cooler.readthedocs.io/en/latest/ and https://academic.oup.com/bioinformatics/article-abstract/36/1/311/5530598?redirectedFrom=fulltext

It would be helpful to extend your tool for the second major file format for Hi-C data besides Juicers .hic. 

Thanks a lot for considering,

Joachim

**Comment by joachimwolff** [comment]
Alright, no answer is also one. That seems to be a 'no, we will not implement this'.

**Comment by thouis** [comment]
Sorry, we don't have many people to support the code.  If you had a pull request for this format, we could probably merge it.
