### ISSUE TITLE
Error in run.neighborhoods.py

### ISSUE THREAD

**Issue by connorrogerson** [broadinstitute/ABC-Enhancer-Gene-Prediction#40]
Hi team,

I came across error when trying to run run.neighborhoods.py. Essentially it can't find the the chom.sizes file because it adds a .bed onto the end.

My code is:
`python /home/cjr78/packages/ABC-Enhancer-Gene-Prediction-0.2.2/src/run.neighborhoods.py \
--candidate_enhancer_regions /rds/user/cjr78/hpc-work/HiC/ABC/CandidateRegions/FlFl/merged_1_2_3_peaks.narrowPeak.candidateRegions.bed \
--genes /rds/user/cjr78/hpc-work/scripts/mm10_refseq_collapsed_genes.bed \
--cellType FlFl \
--outdir /rds/user/cjr78/hpc-work/HiC/ABC/Neighborhoods/FlFl/ \
--H3K27ac /rds/user/cjr78/hpc-work/ChIP/H3K27ac/bam/merged_bams/1_2_3_merged.bam \
--ATAC rds/user/cjr78/hpc-work/ATAC/bowtie/merged/merged_1_2_3.bam \
--expression_table /home/cjr78/rds/hpc-work/HiC/ABC/Input/flfl_tpm.txt \
--chrom_sizes /rds/user/cjr78/hpc-work/scripts/mm10.chrom.sizes`

The error is:
`Namespace(ATAC='rds/user/cjr78/hpc-work/ATAC/bowtie/merged/merged_1_2_3.bam', DHS='', H3K27ac='/rds/user/cjr78/hpc-work/ChIP/H3K27ac/bam/merged_bams/1_2_3_merged.bam', candidate_enhancer_regions='/rds/user/cjr78/hpc-work/HiC/ABC/CandidateRegions/FlFl/merged_1_2_3_peaks.narrowPeak.candidateRegions.bed', cellType='FlFl', chrom_sizes='/rds/user/cjr78/hpc-work/scripts/mm10.chrom.sizes', default_accessibility_feature=None, enhancer_class_override=None, expression_table='/home/cjr78/rds/hpc-work/HiC/ABC/Input/flfl_tpm.txt', gene_name_annotations='symbol', genes='/rds/user/cjr78/hpc-work/scripts/mm10_refseq_collapsed_genes.bed', genes_for_class_assignment=None, outdir='/rds/user/cjr78/hpc-work/HiC/ABC/Neighborhoods/FlFl/', primary_gene_identifier='symbol', qnorm=None, skip_gene_counts=False, skip_rpkm_quantile=False, supplementary_features=None, tss_slop_for_class_assignment=500, ubiquitously_expressed_genes=None, use_secondary_counting_method=False)
Using gene expression from files: ['/home/cjr78/rds/hpc-work/HiC/ABC/Input/flfl_tpm.txt']`

`Traceback (most recent call last):
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-0.2.2/src/run.neighborhoods.py", line 97, in <module>
    main(args)
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-0.2.2/src/run.neighborhoods.py", line 93, in main
    processCellType(args)
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-0.2.2/src/run.neighborhoods.py", line 74, in processCellType
    outdir = args.outdir)
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-0.2.2/src/neighborhoods.py", line 85, in annotate_genes_with_features
    tss1kb = make_tss_region_file(genes, outdir, genome_sizes)
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-0.2.2/src/neighborhoods.py", line 111, in make_tss_region_file
    sizes_pr = df_to_pyranges(read_bed(sizes + '.bed'))
  File "/home/cjr78/packages/ABC-Enhancer-Gene-Prediction-0.2.2/src/neighborhoods.py", line 479, in read_bed
    skip = 1 if ("track" in open(filename, "r").readline()) else 0
FileNotFoundError: [Errno 2] No such file or directory: '/rds/user/cjr78/hpc-work/scripts/mm10.chrom.sizes.bed'`

Bizarrely, if I rename the chrome.sizes file so that it ends with .bed, it can't find it because it's looking for the correct file name!

**Comment by thouis** [comment]
Hi, could you try the `no_promoter_overlaps` branch?  I think that will fix this.

**Comment by connorrogerson** [comment]
This works thanks!
