### ISSUE TITLE
Whether this method is suitable for HiChIP dataset?

### ISSUE THREAD

**Issue by zengyingying2015** [broadinstitute/ABC-Enhancer-Gene-Prediction#42]
Can I just replace the HiC data with HiChIP data? Another question is the default ABC score cutoff is 0.02, I am wondering how to set a suitable ABC score cutoff for different analysis. Thanks a lot.

**Comment by thouis** [comment]
You can probably use Hi-ChIP, though it may take some adjustment for the fact that HiChIP may be biased toward elements with whichever protein is pulled down.

The cutoff of 0.02 was based on our experiments with CRISPRi, and was chosen to optimize Precision at 70% recall.  Other analyses would have to use other experiments and/or criteria to choose a relevant cutoff.
