### ISSUE TITLE
typo in field 'hic_kr' in src/makeAverageHiC.py

### ISSUE THREAD

**Issue by annashch-insitro** [broadinstitute/ABC-Enhancer-Gene-Prediction#43]
makeAverageHiC.py performs several operations on the 'hic_kr' column of the hic file (i.e. https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/master/src/makeAverageHiC.py#L75). However, the hic.py file does not define such a column, referring instead to 'hic_contact' (i.e. https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/master/src/hic.py#L116). Should reference to 'hic_kr' be changed to 'hic_contact'? I am not seeing a 'hic_kr' column in my downloaded hic files, there is just 'bin1','bin2','hic_contact'.

**Comment by thouis** [comment]
Are you encountering an error related to this?  From my reading of the places HiC is loaded, it looks like the ABC code overrides the name:

https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/master/src/hic.py#L55
and 
https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/master/src/hic.py#L149

**Comment by thouis** [comment]
closed for lack of activity.
