### ISSUE TITLE
Use with single-cell ATAC-Seq?

### ISSUE THREAD

**Issue by davidjohngreen** [broadinstitute/ABC-Enhancer-Gene-Prediction#46]
Hi there,

Any ideas about whether ABC can be used with single-cell ATAC-seq data?

Best,

David Green

**Comment by thouis** [comment]
Yes.  I'd suggest using the sc-ATAC to create pseudobulk (with or without evening out reads per-cell) ATAC, and it should work similarly to using bulk ATAC.

**Comment by atancoder** [comment]
We've revamped the codebase. Please check out https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main and reopen your issue if it still exists

We have a section dedicated to scATAC-seq in the ReadTheDocs
