### ISSUE TITLE
Creating acceptable Hi-C input

### ISSUE THREAD

**Issue by MatusV8** [broadinstitute/ABC-Enhancer-Gene-Prediction#47]
Hello,

I would like to ask if it is possible to use contact scores generated by CHICAGO as "contact frequency" in Hi-C bedpe format. I am trying to use capture Hi-C data set to create ABC model but after reading the publications and the github page, It is not clear to me how to get the required input files. I am not sure if it is ok to create genome wide binned matrix (e.g. by Juicer) with capture Hi-C data.

Could you advise me on how could I generate acceptable Hi-C input from capture Hi-C data please?

Many thanks in advance,
Matus

**Comment by atancoder** [comment]
We've revamped the codebase. Please check out https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main and reopen your issue if it still exists
