### ISSUE TITLE
Without H3K27ac from the same samples

### ISSUE THREAD

**Issue by shengxin321** [broadinstitute/ABC-Enhancer-Gene-Prediction#49]
Hi there,
   If I only have bulk ATAC-seq data for samples but without H3K27ac from the same samples? Can I use ATAC-seq data + H3K27ac (for example, just download one data from GEO), then call the enhancers in each sample and predict the ABC interaction? But I still could obtain the individual specific enhancers? due to the overlapped regions between ATAC-seq peaks and the only one H3K27ac peaks are different? Is there any potential issue? 
Thank you.

Best,
Xin

**Comment by thouis** [comment]
Yes, using H3K27ac from the same cell type (but different samples) should be fine.  Or even very similar cell types.  Checking overlap between ATAC peaks, which ABC will usually use to identify potential enhancers, and H3K27ac peaks would be a good check.

**Comment by baishengjun** [comment]
Hi there,

I have a question similar to the one mentioned above. I have individual H3K27ac ChIP-seq samples but lack ATAC-seq data from the same samples. In this case, would it be feasible to use scATAC-seq data (a single file downloaded from GEO) in combination with my H3K27ac ChIP-seq data and Hi-C data to identify enhancers in each sample and predict ABC (Activity-by-Contact) interactions?

Thank you very much for your help!
Best regards,

Bai

**Comment by mayasheth** [comment]
Hi, thanks for the question. 

You should be able to provide the same ATAC-seq file with cell-type specific H3K27ac ChIP and Hi-C data! In your case, "activity" part of ABC will be the geometric mean of ATAC signal and H3K27ac signal, so it will still be specific to your individual samples.
