### ISSUE TITLE
candidateRegions.bed file is empty after use the example code

### ISSUE THREAD

**Issue by cindy264** [broadinstitute/ABC-Enhancer-Gene-Prediction#56]
I  am running the example now. I run the following program:
But the file wgEncodeUwDnaseK562AlnRep1.chr22.macs2_peaks.narrowPeak.sorted.candidateRegions.bed is empty, not sure what I should do

python src/makeCandidateRegions.py \
--narrowPeak example_chr22/ABC_output/Peaks/wgEncodeUwDnaseK562AlnRep1.chr22.macs2_peaks.narrowPeak.sorted \
--bam example_chr22/input_data/Chromatin/wgEncodeUwDnaseK562AlnRep1.chr22.bam \
--outDir example_chr22/ABC_output/Peaks/ \
--chrom_sizes example_chr22/reference/chr22 \
--regions_blocklist reference/wgEncodeHg19ConsensusSignalArtifactRegions.bed \
--regions_includelist example_chr22/reference/RefSeqCurated.170308.bed.CollapsedGeneBounds.TSS500bp.chr22.bed \
--peakExtendFromSummit 250 \
--nStrongestPeaks 3000

**Comment by lmangnier** [comment]
Hi @cindy264, 

Did you find the reason of that ? 
I am curious since I have the same issue on my data.

Cheers,
L

**Comment by FatihSarigol** [comment]
I faced the same problem as well, there was no error or warning and that file got generated to be empty even though this other file is generated exactly the same as the original example output (277KB) without any issue: **wgEncodeUwDnaseK562AlnRep1.chr22.macs2_peaks.narrowPeak.sorted.wgEncodeUwDnaseK562AlnRep1.chr22.bam.Counts.bed**

**Comment by FatihSarigol** [comment]
> Hi @cindy264,
> 
> Did you find the reason of that ? I am curious since I have the same issue on my data.
> 
> Cheers, L

Ok I actually solved it, at least for my case  which I imagine should be rare, but maybe something similar is happening for the next user visiting this issue...
I have an **_alias_** in my **.bashrc** for the bedtools executable location called **bedtools**, and the ABC python script can not access that via **os.system** because it is not on my path _even though for everything else in bash it had caused no issue before_, so I did this which I was already supposed to do in first place:

export PATH=$PATH:/home/Programs/bedtools2/bin/

and the script did generate that empty output file correctly this time

**Comment by bateman153** [comment]
> > Hi @cindy264,
> > Did you find the reason of that ? I am curious since I have the same issue on my data.
> > Cheers, L
> 
> Ok I actually solved it, at least for my case which I imagine should be rare, but maybe something similar is happening for the next user visiting this issue... I have an **_alias_** in my **.bashrc** for the bedtools executable location called **bedtools**, and the ABC python script can not access that via **os.system** because it is not on my path _even though for everything else in bash it had caused no issue before_, so I did this which I was already supposed to do in first place:
> 
> export PATH=$PATH:/home/Programs/bedtools2/bin/
> 
> and the script did generate that empty output file correctly this time

hi @FatihSarigol , 
I met the same issue and I'm glad to find that you've solved the problem.
I'd like to try your method but before that, I want to know how you figured out the problem, so I can make sure that our case are exactly the same.
