### ISSUE TITLE
Is it possible to include HiC data for GRCh38?

### ISSUE THREAD

**Issue by gaoyuanwang1976** [broadinstitute/ABC-Enhancer-Gene-Prediction#64]
Hi dear developers of the ABC model,
I'm using ABC model for data of build GRCh38. 
Up to now, I was only able to run predict.py without using HiC data and only with power law estimate. 
For a quantitative comparison with other results, I would like to also run predict.py with HiC data. However, juicebox_dump.py seems to be unable to process GRCh38 HiC. Is there a way to workaround for using GRCh38? 
Do you have an average HiC for GRCh38?
Thank you

**Comment by koh2ng0** [comment]
@gaoyuanwang1976 Hi, Did you find any solutions for your question?

**Comment by atancoder** [comment]
We've revamped the codebase. Please check out https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main and reopen your issue if it still exists

average HiC is available in the linked ReadTheDocs in the detailed methods section
