### ISSUE TITLE
How to make the average Hi-C profiles for hg38

### ISSUE THREAD

**Issue by koh2ng0** [broadinstitute/ABC-Enhancer-Gene-Prediction#67]
Hi,
I tried to make the average Hi-C profile for hg38. So, I downloaded the hic files of 10 cell types for hg38 and created "KRobserved.gz" and "KRnorm.gz", respectively. Then I ran the 'makeAverageHic.py' and got the "avg.gz". But the 'predict.py' requires two Hi-C files, "~.KRobserved.gz" and "~.KRnorm.gz".
I don't know what I can do for the next step, so could I get advice for this situation, please?

**Comment by zzhoujialu** [comment]
Hi, I have met the same problem. Have you solved that yet?
Looking forward to hearing from you!  :)

**Comment by atancoder** [comment]
We've revamped the codebase. Please check out https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main and reopen your issue if it still exists

we mention how to use average Hi-C in the detailed methods of ReadTheDocs
