### ISSUE TITLE
KeyError: 'ABC.Score' - predict.py fails to set the score column

### ISSUE THREAD

**Issue by Bennibraun** [broadinstitute/ABC-Enhancer-Gene-Prediction#69]
I'm running the final step of the pipeline as follows:

```
python ~/scratch/atacseq/abc/ABC-Enhancer-Gene-Prediction/src/predict.py \
--enhancers Neighborhoods/WT/EnhancerList.txt \
--genes Neighborhoods/WT/GeneList.txt \
--chrom_sizes ~/ref_annots/hg19.chrom.sizes \
--threshold .02 \
--cellType U937 \
--outdir Predictions/ \
--make_all_putative
```

When it starts writing output files, I'm getting an error indicating that the 'ABC.Score' column doesn't exist in the dataframe. I have added a debug printout of the dataframe's columns at that point:

```
Index(['chr', 'start', 'end', 'name', 'class', 'activity_base', 'enh_midpoint',
       'enh_idx', 'TargetGene', 'TargetGeneTSS', 'TargetGeneExpression',
       'TargetGenePromoterActivityQuantile', 'TargetGeneIsExpressed',
       'gene_idx', 'distance', 'isSelfPromoter', 'powerlaw_contact',
       'powerlaw_contact_reference', 'powerlaw.Score.Numerator',
       'powerlaw.Score', 'CellType'],
      dtype='object')
```

And here is the error message:

```
Traceback (most recent call last):
  File "/home/beb528/.conda/envs/final-abc-env/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'ABC.Score'
```

I've looked through the function calls and couldn't find any code that fills the score column (args.score_column). Is there something wrong with my inputs, or might this be a bug?

**Comment by Cengoni** [comment]
Hi, I encountered the same issue but it turned out that there is an argument (--score_column powerlaw.Score) you should use in predict.py when you are running the model without contact data, it is explained in one of the last sections of the README [(abc model without experimental contact data)](https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction#abc-model-without-experimental-contact-data).
Hope this helps!

**Comment by Bennibraun** [comment]
Thank you so much! This solved my issue, I think it was confusing because predict.py was already declaring that it would be running with the powerlaw score despite --score_column powerlaw.Score not being set. Appreciate the help!
