### ISSUE TITLE
KeyError: 'end' with run.neighborhoods.py

### ISSUE THREAD

**Issue by pgh10** [broadinstitute/ABC-Enhancer-Gene-Prediction#70]
The code runs fine with the example inputs but fails with KeyError using own inputs. Traced the problem back to my mm10 gene file and chromosome size file. Recreated both and ensured no trailing spaces but the error persists. Does anyone have a RefSeq mm10 bed file and chr.size file they've used successfully with run.neighborhoods?

**Comment by peneder** [comment]
Hi! I had the same problem but could fix it by ensuring that the chromsizes file has three columns: chromosome, start, end. Start is always 0 (see the example file used in the tutorial). My files only had the chromosome and end column, that caused the error. After adding the start column (just zeroes) it worked.

**Comment by atancoder** [comment]
We've revamped the codebase. Please check out https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/tree/main and reopen your issue if it still exists
