### ISSUE TITLE
gzip: stdout: Broken pipe

### ISSUE THREAD

**Issue by wbszhu** [broadinstitute/ABC-Enhancer-Gene-Prediction#74]
Hi, 
I came across an issue in the [predict ](https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/master/src/predict.py#L134)step where the following error appeared:
```
gzip: stdout: Broken pipe
```
Directly compressing the result file into a gz format file using gzip does not seem like a good idea.
LuZhang

**Comment by wbszhu** [comment]
Hi, I have solved it.
check this [line](https://github.com/broadinstitute/ABC-Enhancer-Gene-Prediction/blob/b6f23f3118216d721bd4abb19fec21e6fa38fdd5/src/getVariantOverlap.py#L29:~:text=os.system(,chrom_sizes%2C%20variant_overlap_file)) , and replace them with
```
import  subprocess
subprocess.check_call("zcat {}.tmp | head -1 | gzip > {}".format(variant_overlap_file, variant_overlap_file), shell=True)
subprocess.check_call("zcat {}.tmp | sed 1d | bedtools slop -b -150 -g {} | gzip >> {}".format(variant_overlap_file, args.chrom_sizes, variant_overlap_file), shell=True)
```
I hope this is useful for you.

**Comment by Sungryong-Oh** [comment]
Thanks! It works for me! I appreciate for your help.
