### ISSUE TITLE
EnhancerList and GeneList chromosomes must start with "chr"

### ISSUE THREAD

**Issue by DustinSokolowski** [broadinstitute/ABC-Enhancer-Gene-Prediction#76]
Hello! Thank you for the fantastic noot. I've been using ABC for non-model organisms whose chromosomes don't start with the "chr" prefix. predict.py will not run unless the chr column of EnhancerList.txt and GeneList.txt has the "chr" prefix attached to each chromosome name. Manually adding the prefix did the trick for me, but non-model organism users should keep an eye out for this as the thrown error looks unrelated.

The chr prefix error that was thrown for me.

`hic_file = os.path.join(hic_dir, chromosome, chromosome + ".KRobserved.gz")`

**Comment by atancoder** [comment]
yeah the code makes a lot of assumptions about the chromosome naming format. We may try to change things in the future to be more flexible with chromosome names
